### ISSUE TITLE
The getter/setter expression section can not work with struct

### ISSUE THREAD

**Issue by WeihanLi** [zzzprojects/ExpressionTree-Tutorial#5]
The getter/setter expression section can not work with struct, should you add a constraint like `where T:class`?

**Comment by JonathanMagnan** [comment]
Hello @WeihanLi ,

Thank for reporting, we will review this page since it should use a propertyName (a `string`) instead of directly the property to make this example make sense.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @WeihanLi ,

The code has been updated to include the `where T: class`. It should be available the next time the page is cached.

Thank again for reporting.

Best Regards,

Jonathan
